---
title: "ds_hw5"
author: "Ditian Li"
date: "2018年11月6日"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

```{r p1-1}
list.files("./data/")
files <- list.files(path = "./data/", pattern = "*.csv")

```

```{r p1-2}
get_data <- function(i) {
  read.csv(paste0("./data/", i))
}

mydata<- files %>% 
  map(get_data) %>%
  reduce(rbind) %>% 
  janitor::clean_names()

mydata$type <- c(rep("con",10), rep("exp",10))
mydata$id <- c(rep(1:10,2))
mydata$study_id = paste0(mydata$type, mydata$id)
mydata <- mydata %>%
  gather(key = week, value = data, week_1:week_8) %>%  
  mutate(week = gsub("_", "", week))


```



```{r}
mydata %>% 
  group_by(study_id) 

mydata %>% 
  ggplot(aes(x = week, y = data)) + 
    geom_line(aes(colour = study_id, group = study_id, linetype = type)) +
    theme(legend.position = "left") +
    labs(
      title = "Spaghetti plot of observations on each subject over week",
      x = "Week",
      y = "Observations"
    )
```

comment: From the plot, we can conclude that the trend of experimental group is roughly increased, the trend of control group is decreased, and experimental group has larger observations than control group overall.
```{r p2}

```

